### ISSUE TITLE
How to set up vasp on a cluster

### ISSUE THREAD

**Issue by zezhong-zhang** [jkitchin/vasp#40]
Dear John,

I am going to setup the code on a cluster (Redhat Linux 2 with SLURM as the job manager), where VASP is already installed as a module. The PATH and PYTHONPATH are also set in .bashrc as instructed. 

I am wondering how to configure the code in details? I noticed that it might need to change the directories of VASP in the vasprc.py file. Though I used to try it on my mac and poped up many error messages...

Thanks for your kind helps,

Zezhong

**Comment by yqshao** [comment]
Basically, you had to setup the `VASP_PP_PATH`  in addition to what you've mentioned. 

However, since you're using a different scheduler, the setup will not be trivial.
I think this repo supports PBS scheduler only and there's a fork by Prateek which supports SGE, both are quite different to slurm.

You will have to tweak the `runner.py` unless you can alter your scheduler on your cluster.
At least you have to change the ` calculate()`  and  `in_queue()` function to do basic job submits.
You can refer to Prateek's fork  https://github.com/prtkm/vasp as a templete to make another scheduler.

**Comment by jkitchin** [comment]
There are a few options you can consider.

The simplest might be to set VASPRC['mode'] = 'run' in your script

and then set VASPRC['vasp.executable.serial'] = 'path/to/some/script'

where path/to/some/script is responsible for running vasp in your environment, including setting up the parallel environment. 

Then you will submit a regular python script to your queue. This doesn't automatically submit the jobs, but I am pretty sure it would work.

To get vaspy to automatically submit jobs it is likely you would have to create a modified version of runner.py. The modifications would include using the slurm env vars, and modifying the subprocess commands for slurm commands. I am not sure you can write to stdin on the slurm job submission command, so you may have to create a tempfile for the job, and then submit the tempfile. Finally, you may have to modify the in_queue command to check if the job is running, and the code that saves the jobid to the calculation database.
